### ISSUE TITLE
Equipment set item filter does not work

### ISSUE THREAD

**Issue by Elberet** [doadin/Baggins#119]
The equipment set item filter does not appear to work in Cataclysm Classic. I have several equipment sets for my character for various activities - default, fishing, cooking, RP - and those sets are listed correctly, but despite selecting any combination of sets or the "Any" option, the filter does not match any items, regardless of the equipment set or sets they belong to.

Since each change of any of the filter's checkboxes triggered #118, I did a `/reload` after each change to test the filter's functionality.

This was observed on Cataclysm Classic with Baggins 5.4.1 with the english language client.
I have not tested this filter with any previous version of Baggins.

**Comment by doadin** [comment]
The equipment set filter does not work very well on retail either. I have had an issue open (https://github.com/Stanzilla/WoWUIBugs/issues/351) for a long time. I honestly don't know if it is a me issue or game issue or what, I know the filter used to work then at some point it stoped.

**Comment by Elberet** [comment]
The API is all kinds of weird. The documentation I found does not match reality on Cataclysm Classic, and at least one method used in the filter's `Matches` does not exist at all.

While I've been looking through the code, I've also noticed another wart that should've popped up sooner: equipment sets are always character-specific, but Baggins profiles may not be and, at least for me, usually never are, so giving the equipment set filter that option is somewhat problematic. Would it be possible to make that part of the filter config character-specific, even if the profile itself isn't? Would that even make sense?

**Comment by Elberet** [comment]
FWIW, I think I can get the equipment set filter to work, but I'll hold off until the other current issues have been closed.

**Comment by doadin** [comment]
I have reverted a change that triggered several issue I did not find in testing, please let me know if [v5.4.6](https://github.com/doadin/Baggins/releases/tag/v5.4.6) works?

**Comment by doadin** [comment]
I have fixed that error if you could test again?

**Comment by doadin** [comment]
https://github.com/doadin/Baggins/commit/6768f94b3d5540ddca390d0c9e0de3380fab6b1d

**Comment by Elberet** [comment]
Yes, the LUA error is gone, but rule updates still don't trigger the refresh correctly, i.e. it still takes a `BAG_UPDATE` game event for Baggins to update.

**Comment by doadin** [comment]
From what I noticed in testing function Baggins:Baggins_CategoriesChanged() calls function Baggins:Baggins_RefreshBags() and at least for the "temp disable cmopression" option bags did not change unless I commented out "sectionframe.dirty" part of function Baggins:Baggins_RefreshBags() . Not sure if this would help on category change or if its a "proper" fix.

**Comment by Elberet** [comment]
I'm going to actually play the game now for a bit, but after that I'll read through the refresh logic and see what I can find. After all, refreshes triggered from `BAG_UPDATE` events correctly update Baggins, so the codepaths for events and programmatic refreshes must diverge somewhere.

**Comment by doadin** [comment]
Thanks for all your help, I have been trying to work on a few things and part of that is tracking down which functions get called where and I have noticed it is a bit of a mess and some times one function only exists to call another, making it harder to track things down, I have been trying to eliminate things like this.

**Comment by doadin** [comment]
Tested the new filter code you PR'd on retail and cata, it only seems to suffer from the same not updating bag frames issue as others so closeing this and other issues that are similar to track in one place: https://github.com/doadin/Baggins/issues/124
