### ISSUE TITLE
Retail - Binding checks appear to have issues

### ISSUE THREAD

**Issue by ryannotfound** [doadin/Baggins#72]
Having reset my profile since the recent update(s), I'm finding it hard to recreate some of my previous filters.

One such check is on binding. My filter is as follows:

Name: Weapons-BOE
Category: Weapons (using existing weapons category check)
AND
Binding: Binds when equipped

Creating the filter works fine, however, trying to apply this to a category produces the error(s) below. Additionally, when I try to open the bags, it also fails (shows only a single item - no bug produced in bugsack), however, reloading UI will prevent opening of bags entirely until this rule is unassigned / category deleted.

26x Interface/AddOns/Baggins/src/filters/ItemBind.lua:25: attempt to call global 'GetContainerItemInfo' (a nil value)
[string "@Interface/AddOns/Baggins/src/filters/ItemBind.lua"]:25: in function `Matches'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:328: in function <Interface/AddOns/Baggins/Baggins-Filtering.lua:299>
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:378: in function `OnSlotChanged'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:289: in function `CheckSlotsChanged'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:439: in function `ForceFullUpdate'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:433: in function `ForceFullRefresh'
[string "@Interface/AddOns/Baggins/Baggins-Options.lua"]:2844: in function `OnProfileEnable'
[string "@Interface/AddOns/Baggins/Baggins.lua"]:497: in function <Interface/AddOns/Baggins/Baggins.lua:435>
[string "=[C]"]: ?
[string "@Interface/AddOns/Baggins/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Baggins/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Baggins/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ce/AddOns/Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by ryannotfound** [comment]
wanted to mention this issue still present following v4.4.4 release

**Comment by doadin** [comment]
should be fixed: https://github.com/doadin/Baggins/commit/a981959cf2e16ee73b8e7eae9ea3bc0b9d2186f5

**Comment by ryannotfound** [comment]
still not working - creating the filter works but applying to a bag does not - same example as above. 


4x Usage: local containerInfo = C_Container.GetContainerItemInfo(containerIndex, slotIndex)
[string "=[C]"]: ?
[string "@Interface/AddOns/Baggins/src/filters/ItemBind.lua"]:26: in function `Matches'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:328: in function <Interface/AddOns/Baggins/Baggins-Filtering.lua:299>
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:378: in function `OnSlotChanged'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:289: in function `CheckSlotsChanged'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:439: in function `ForceFullUpdate'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:433: in function `ForceFullRefresh'
[string "@Interface/AddOns/Baggins/Baggins.lua"]:3879: in function `AddCategory'
[string "@Interface/AddOns/Baggins/Baggins-Options.lua"]:3029: in function <Interface/AddOns/Baggins/Baggins-Options.lua:3026>
[string "=[C]"]: ?
[string "@Interface/AddOns/Baggins/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Baggins/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/TomTom/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/TomTom/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/TomTom/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/TomTom/libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown.lua"]:432: in function <...om/libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown.lua:423>
[string "=[C]"]: ?
[string "@Interface/AddOns/TomTom/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/TomTom/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/TomTom/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/TomTom/libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown-Items.lua"]:351: in function <...s/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:341>

**Comment by doadin** [comment]
Should be fixed: https://github.com/doadin/Baggins/commit/96aa2654709904add291f74d9b428d5d43dd6aad 
Sorry about that.

**Comment by ryannotfound** [comment]
Afraid this still has issues - v4.4.9 still producing the errors below. For a quick test, you can create a new category, and assign it BIND and then ACCOUNT BOUND (i have some BOA stuff in my bags right now from prepatch event). Again creation of the category works fine, however, when you try to apply the category to a bag section, bugsack error is thrown and bags refuse to open until it is removed.


10x Usage: local containerInfo = C_Container.GetContainerItemInfo(containerIndex, slotIndex)
[string "=[C]"]: ?
[string "@Interface/AddOns/Baggins/src/filters/ItemBind.lua"]:26: in function `Matches'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:328: in function <Interface/AddOns/Baggins/Baggins-Filtering.lua:299>
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:378: in function `OnSlotChanged'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:289: in function `CheckSlotsChanged'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:439: in function `ForceFullUpdate'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:433: in function `ForceFullRefresh'
[string "@Interface/AddOns/Baggins/Baggins.lua"]:3879: in function `AddCategory'
[string "@Interface/AddOns/Baggins/Baggins-Options.lua"]:3029: in function <Interface/AddOns/Baggins/Baggins-Options.lua:3026>
[string "=[C]"]: ?
[string "@Interface/AddOns/Baggins/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Baggins/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/TomTom/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/TomTom/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/TomTom/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/TomTom/libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown.lua"]:432: in function <...om/libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown.lua:423>
[string "=[C]"]: ?
[string "@Interface/AddOns/TomTom/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/TomTom/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/TomTom/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/TomTom/libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown-Items.lua"]:351: in function <...s/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:341>

**Comment by doadin** [comment]
That is odd I am not gettnig this error.

**Comment by doadin** [comment]
I think I know the issue working on it.

**Comment by ryannotfound** [comment]
Thanks - for additional context, can 100% confirm this occurs on brand new profile (reset in the options) - also tested on a boosted character with no items (moved every item to bank, nothing in inventory or equipped). 

Again, here is my process: (from new profile)

1. Enter Bag/Category Config
2. Create Category ("Test")
3. Type: Bind
4. Bind Type: Account Bound (can probably be any binding)
5. In Bag/Category Config, click Bags->Other
6. Click New Section
7. Expand Other to see sections, click "New" (newly created section)
8. From Categories dropdown, select "Test"
9. Immediate error occurs

Hope this helps.

**Comment by doadin** [comment]
I was so lost with all the updates I was doing, yes v4.4.9 does NOT include that fix so yes it will still exist. I just pushed v4.5.0 that one DOES include the fix.

**Comment by ryannotfound** [comment]
This is no longer triggering a bugsack error, however, the sorting isnt working for these as if the binding match is ignored.

Quick way to test this is to create a BOA category and apply it to a bag section. Give that section a priority of 20 and then create an Heirloom. This is an account bound item but it is not being sorted into the section with the category applied.

I have my other categories which are also not working with binding, for example, BOE weapons, BOE armor, etc.. I use these to match category weapons (category armor for boe armors) + binding BOE, and give it a higher priority, and it does not move the items into my BOE armor/weapons section, etc..

Thanks for your effort in fixing this, btw!

**Comment by doadin** [comment]
please check 4.5.1

**Comment by ryannotfound** [comment]
Thanks very much - looks like BOE/soulbound/unbound filters are now working - I don't have any bind on use items to check. Still appears to be an issue on account bound items, though - Even a simple filter with just BOA at very high priority will still not sort it into the proper sections. That looks like the last issue with this. For the moment I am able to workaround this by doing a tooltip check for "Account Bound" which does catch.

FWIW I am glad you ditched the tooltip library and have your own functions for tooltip searches now. I previously could not filter on the subitem blue text in items, like "Mechagon Tinkering", which I am able to do so now, so huge QoL improvement there!

**Comment by doadin** [comment]
Could you provide a name for a BOA item that is not working so I can test?

**Comment by ryannotfound** [comment]
Burnished Helm of Might (heirloom plate helmet)

**Comment by doadin** [comment]
Thank you!

**Comment by doadin** [comment]
I believe this is an issue with the game client api https://github.com/Stanzilla/WoWUIBugs/issues/349

**Comment by doadin** [comment]
I have added that as a workaround for the filter so it should work now without needed a seperate, if you could please test thanks!
https://github.com/doadin/Baggins/commit/607510494405dd0a9e27dfd4cf975bea191a7c88

**Comment by ArPharazon** [comment]
I have updated to version 4.5.9 and still getting the filtering error:

`67x Interface/AddOns/Baggins/src/filters/ItemBind.lua:46: attempt to call global 'C_TooltipInfoGetBagItem' (a nil value)
[string "@Interface/AddOns/Baggins/src/filters/ItemBind.lua"]:46: in function `Matches'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:329: in function <Interface/AddOns/Baggins/Baggins-Filtering.lua:300>
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:319: in function <Interface/AddOns/Baggins/Baggins-Filtering.lua:300>
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:379: in function `OnSlotChanged'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:290: in function `CheckSlotsChanged'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:440: in function `ForceFullUpdate'
[string "@Interface/AddOns/Baggins/Baggins-Filtering.lua"]:434: in function `ForceFullRefresh'
[string "@Interface/AddOns/Baggins/Baggins-Options.lua"]:2844: in function `OnProfileEnable'
[string "@Interface/AddOns/Baggins/Baggins.lua"]:499: in function <Interface/AddOns/Baggins/Baggins.lua:437>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>`

**Comment by doadin** [comment]
Hopefully I fixed this in v4.6.0, I am really fumbling lately.

**Comment by ArPharazon** [comment]
I have upgraded to v4.6.0 and can confirm that its fixed.

Thanks heaps for that - really appreciate it.
